name: custom-puppeteer-image
on:
  push:
    branches:
      - main

jobs:
  deploy-latest:
    permissions: write-all
    name: deploy-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
            docker build -t c-pupe:latest .

      - name: Link Docker Tag
        run: |
            docker tag c-pupe:latest calixtodazs/c-pupe:latest

      - name: Push Docker Image
        run: |
            docker push calixtodazs/c-pupe:latest